enum WaypointTraitSymbol {
  UNCHARTED._('UNCHARTED'),
  UNDER_CONSTRUCTION._('UNDER_CONSTRUCTION'),
  MARKETPLACE._('MARKETPLACE'),
  SHIPYARD._('SHIPYARD'),
  OUTPOST._('OUTPOST'),
  SCATTERED_SETTLEMENTS._('SCATTERED_SETTLEMENTS'),
  SPRAWLING_CITIES._('SPRAWLING_CITIES'),
  MEGA_STRUCTURES._('MEGA_STRUCTURES'),
  PIRATE_BASE._('PIRATE_BASE'),
  OVERCROWDED._('OVERCROWDED'),
  HIGH_TECH._('HIGH_TECH'),
  CORRUPT._('CORRUPT'),
  BUREAUCRATIC._('BUREAUCRATIC'),
  TRADING_HUB._('TRADING_HUB'),
  INDUSTRIAL._('INDUSTRIAL'),
  BLACK_MARKET._('BLACK_MARKET'),
  RESEARCH_FACILITY._('RESEARCH_FACILITY'),
  MILITARY_BASE._('MILITARY_BASE'),
  SURVEILLANCE_OUTPOST._('SURVEILLANCE_OUTPOST'),
  EXPLORATION_OUTPOST._('EXPLORATION_OUTPOST'),
  MINERAL_DEPOSITS._('MINERAL_DEPOSITS'),
  COMMON_METAL_DEPOSITS._('COMMON_METAL_DEPOSITS'),
  PRECIOUS_METAL_DEPOSITS._('PRECIOUS_METAL_DEPOSITS'),
  RARE_METAL_DEPOSITS._('RARE_METAL_DEPOSITS'),
  METHANE_POOLS._('METHANE_POOLS'),
  ICE_CRYSTALS._('ICE_CRYSTALS'),
  EXPLOSIVE_GASES._('EXPLOSIVE_GASES'),
  STRONG_MAGNETOSPHERE._('STRONG_MAGNETOSPHERE'),
  VIBRANT_AURORAS._('VIBRANT_AURORAS'),
  SALT_FLATS._('SALT_FLATS'),
  CANYONS._('CANYONS'),
  PERPETUAL_DAYLIGHT._('PERPETUAL_DAYLIGHT'),
  PERPETUAL_OVERCAST._('PERPETUAL_OVERCAST'),
  DRY_SEABEDS._('DRY_SEABEDS'),
  MAGMA_SEAS._('MAGMA_SEAS'),
  SUPERVOLCANOES._('SUPERVOLCANOES'),
  ASH_CLOUDS._('ASH_CLOUDS'),
  VAST_RUINS._('VAST_RUINS'),
  MUTATED_FLORA._('MUTATED_FLORA'),
  TERRAFORMED._('TERRAFORMED'),
  EXTREME_TEMPERATURES._('EXTREME_TEMPERATURES'),
  EXTREME_PRESSURE._('EXTREME_PRESSURE'),
  DIVERSE_LIFE._('DIVERSE_LIFE'),
  SCARCE_LIFE._('SCARCE_LIFE'),
  FOSSILS._('FOSSILS'),
  WEAK_GRAVITY._('WEAK_GRAVITY'),
  STRONG_GRAVITY._('STRONG_GRAVITY'),
  CRUSHING_GRAVITY._('CRUSHING_GRAVITY'),
  TOXIC_ATMOSPHERE._('TOXIC_ATMOSPHERE'),
  CORROSIVE_ATMOSPHERE._('CORROSIVE_ATMOSPHERE'),
  BREATHABLE_ATMOSPHERE._('BREATHABLE_ATMOSPHERE'),
  THIN_ATMOSPHERE._('THIN_ATMOSPHERE'),
  JOVIAN._('JOVIAN'),
  ROCKY._('ROCKY'),
  VOLCANIC._('VOLCANIC'),
  FROZEN._('FROZEN'),
  SWAMP._('SWAMP'),
  BARREN._('BARREN'),
  TEMPERATE._('TEMPERATE'),
  JUNGLE._('JUNGLE'),
  OCEAN._('OCEAN'),
  RADIOACTIVE._('RADIOACTIVE'),
  MICRO_GRAVITY_ANOMALIES._('MICRO_GRAVITY_ANOMALIES'),
  DEBRIS_CLUSTER._('DEBRIS_CLUSTER'),
  DEEP_CRATERS._('DEEP_CRATERS'),
  SHALLOW_CRATERS._('SHALLOW_CRATERS'),
  UNSTABLE_COMPOSITION._('UNSTABLE_COMPOSITION'),
  HOLLOWED_INTERIOR._('HOLLOWED_INTERIOR'),
  STRIPPED._('STRIPPED');

  const WaypointTraitSymbol._(this.value);

  factory WaypointTraitSymbol.fromJson(String json) {
    return WaypointTraitSymbol.values.firstWhere(
      (value) => value.value == json,
      orElse: () =>
          throw FormatException('Unknown WaypointTraitSymbol value: $json'),
    );
  }

  /// Convenience to create a nullable type from a nullable json object.
  /// Useful when parsing optional fields.
  static WaypointTraitSymbol? maybeFromJson(String? json) {
    if (json == null) {
      return null;
    }
    return WaypointTraitSymbol.fromJson(json);
  }

  final String value;

  String toJson() => value;

  @override
  String toString() => value;
}
