# This file configures the static analysis results for your project (errors,
# warnings, and lints).

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
  # Don't warn about lints in generated code.
    - '**/*.g.dart'
