name: types
description: Types layer.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  # Must match Flutter verion dependencies.
  collection: ^1.17.1
  intl: ^0.17.0
  # We only want the model types.
  meta: ^1.9.1
  # Flutter 3.13.0 is pinned to collection 1.17.2
  # So we can't use more 4.0.1+ until Flutter upgrades collection.
  more: ^4.0.0
  openapi:
    path: ../openapi
  yaml: ^3.1.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0