name: types
description: Types layer.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0
# resolution: workspace

# dependency versions should match Flutter to allow `ui` to depend on Flutter.
dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  # http is only needed for Response object for QueueResponse.
  http: ^0.13.6
  intl: ^0.20.2
  meta: ^1.9.1
  more: ^4.0.0
  # Ideally we'd only import the OpenAPI model types.
  openapi:
    path: ../openapi

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
