include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    # An experimental rule that very_good_analysis shouldn't have on.
    specify_nonobvious_property_types: false
    # This lint is wrong.  It changes behavior to pass the future
    # out, making exceptions happen in the outer scope.
    unnecessary_await_in_return: false