$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - "**/build/**"
  - "packages/cli/static_data"
  - "packages/cli/data"
  - "packages/openapi"
  - "*.sql"
  - "db_data"
words:
  - leaderboards
  - lookback
  - psql
  - spacetraders
  - mocktail
  - siphoner
  - jumpgate
  - microtask
  - eseidel
  - healthz
  - upsert
  - sqls
  - systrace
  - cooldowns
  - jumpgates
  - cooldown
  - siphoners
  - pathing
  - upcycle
  - AFAICT
  - PGPASSWORD
  - PGUSER
  - cooldown
  - undock
  - siphonable
  - HYPERGIANT
  - screenrc
  - MERITIUM
  - Opps
  - Seidel
  - genhtml
  - sublist
  - codegen
  - URANITE
  - writeln
  - undocked
  - ratelimit
  - stddev
  - vcpu
  - ASTRO
  - ARGB
  - LTRB
  - Multiset
  - endtemplate
  - termcapinfo
  - cupertino
  - Unstreamed
  - SAF
  - chalkdart
  - cirruslabs
  - pubspec
  - templating
  - PGHOST
  - bigserial
  - upsert
  - upserts
  - polynucleotides
  - biocomposites
  - supergrains
  - holographics
  - supervolcanoes
  - Brubaker
  - MICROABRASIONS
  - FEBA
  - newtype
  - contentful
  - specify_nonobvious_property_types