# Configuration options:
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/dart.md
# Also:
# openapi-generator config-help -g dart

# These names I inferred from https://github.com/OpenAPITools/openapi-generator/blob/master/docs/configuration.md
# but they seem to work:
inputSpec: https://raw.githubusercontent.com/SpaceTradersAPI/api-docs/b52734a2cdb63e796174310ebac89f5009df3b9f/reference/SpaceTraders.json
outputDir: packages/space_traders_api
generatorName: dart

# Dart specific config:
pubAuthor: Eric Seidel
pubAuthorEmail: eric@shorebird.dev
pubDescription: SpaceTraders API (v2)
pubRepository: https://github.com/eseidel/space_traders
pubLibrary: space_traders_api
pubPublishTo: none