# These names I inferred from https://github.com/OpenAPITools/openapi-generator/blob/master/docs/configuration.md
# but they seem to work:
# fails: c83c8ec844bcf232b35acf7b415c8eb4d2e82526
inputSpec: https://raw.githubusercontent.com/SpaceTradersAPI/api-docs/6ee89f81cb876f05ffd94632a92e4fd8b92ced20/reference/SpaceTraders.json
outputDir: packages/space_traders_api
generatorName: dart

# Dart specific config:
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/dart.md
# Also:
# openapi-generator config-help -g dart
pubName: space_traders_api
pubAuthor: Eric Seidel
pubAuthorEmail: eric@shorebird.dev
pubDescription: SpaceTraders API (v2)
pubRepository: https://github.com/eseidel/space_traders
pubLibrary: space_traders_api
pubPublishTo: none