# These names I inferred from https://github.com/OpenAPITools/openapi-generator/blob/master/docs/configuration.md
# but they seem to work:
inputSpec: https://api.staging.spacetraders.io/v2/documentation/json
outputDir: packages/openapi
generatorName: dart

# Dart specific config:
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/dart.md
# Also:
# openapi-generator config-help -g dart
pubName: openapi
pubAuthor: Eric Seidel
pubAuthorEmail: eric@shorebird.dev
pubDescription: SpaceTraders API
pubRepository: https://github.com/eseidel/space_traders
pubLibrary: openapi
pubPublishTo: none