# These names I inferred from https://github.com/OpenAPITools/openapi-generator/blob/master/docs/configuration.md
# but they seem to work:
inputSpec: https://raw.githubusercontent.com/SpaceTradersAPI/api-docs/e3f70c77290918953d19b121e1e9b75c39ad6c5f/reference/SpaceTraders.json
outputDir: packages/openapi
generatorName: dart

# Dart specific config:
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/dart.md
# Also:
# openapi-generator config-help -g dart
pubName: openapi
pubAuthor: Eric Seidel
pubAuthorEmail: eric@shorebird.dev
pubDescription: SpaceTraders API
pubRepository: https://github.com/eseidel/space_traders
pubLibrary: openapi
pubPublishTo: none