name: space_traders_cli
description: A command line interface to spacetraders.io
version: 1.0.0
publish_to: none
repository: https://github.com/eseidel/space_traders

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.2
  file: ^6.1.4
  http: ^0.13.6
  intl: ^0.17.0
  mason_logger: ^0.2.5
  sembast: ^3.4.4
  space_traders_api:
    path: ../space_traders_api
  stats: ^2.0.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.0
  very_good_analysis: ^4.0.0
