name: protocol
description: Protocol and view models for server.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.9.5
  test: ^1.24.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6