name: protocol
description: Protocol and view models for server.
version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.0
# resolution: workspace

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  types:
    path: ../types

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.9.5
  test: ^1.24.0
  very_good_analysis: ^7.0.0
