DROP TABLE IF EXISTS "request_" CASCADE;
DROP TABLE IF EXISTS "response_" CASCADE;
DROP TABLE IF EXISTS "transaction_" CASCADE;
DROP TABLE IF EXISTS "survey_" CASCADE;
DROP TABLE IF EXISTS "faction_" CASCADE;
DROP TABLE IF EXISTS "behavior_" CASCADE;
DROP TABLE IF EXISTS "extraction_" CASCADE;