name: server
description: Backend for the ui.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cli:
    path: ../cli
  dart_frog: ^1.1.0
  db:
    path: ../db
  file: ^7.0.1
  protocol:
    path: ../protocol

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.0.0
