# This file configures the static analysis results for your project (errors,
# warnings, and lints).

include: ../../analysis_options.yaml
linter:
  rules:
    # An experimental rule that very_good_analysis shouldn't have on.
    specify_nonobvious_property_types: false
