name: ui
description: UI for SpaceTraders.io
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0
# resolution: workspace

dependencies:
  client:
    path: ../client
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  file: ^7.0.0
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  http: ^1.4.0
  protocol:
    path: ../protocol
  types:
    path: ../types

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true