name: cli
description: A command line interface to spacetraders.io
version: 1.0.0
publish_to: none
repository: https://github.com/eseidel/space_traders

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.1
  async: ^2.11.0
  clock: ^1.1.1
  collection: ^1.17.1
  db:
    path: ../db
  fake_async: ^1.3.1
  file: ^6.1.4
  http: ^0.13.6
  intl: ^0.17.0
  json_diff: ^0.2.1
  mason_logger: ^0.2.5
  meta: ^1.9.1
  openapi:
    path: ../openapi
  postgres: ^2.6.2
  scoped:
    git:
      url: https://github.com/shorebirdtech/shorebird.git
      path: packages/scoped
  sembast: ^3.4.4
  stats: ^2.0.0
  types:
    path: ../types
  yaml: ^3.1.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0
