name: cli
description: A command line interface to spacetraders.io
version: 1.0.0
publish_to: none
repository: https://github.com/eseidel/space_traders

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.1
  cli_table: ^1.0.2
  collection: ^1.17.1
  db:
    path: ../db
  equatable: ^2.0.5
  file: ^7.0.0
  http: ^0.13.6
  intl: ^0.18.0
  json_diff:
    git:
      # The original package is no longer maintained.
      url: https://github.com/eseidel/dart-json_diff.git
  mason_logger: ^0.2.5
  meta: ^1.9.1
  openapi:
    path: ../openapi
  path: ^1.8.3
  scoped:
    git:
      url: https://github.com/shorebirdtech/shorebird.git
      path: packages/scoped
  stats: ^2.0.0
  types:
    path: ../types
  yaml: ^3.1.2

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.21.0
  very_good_analysis: ^5.1.0
