name: cli
description: A command line interface to spacetraders.io
version: 1.0.0
publish_to: none
repository: https://github.com/eseidel/space_traders

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.1
  async: ^2.11.0
  clock: ^1.1.1
  collection: ^1.17.1
  fake_async: ^1.3.1
  file: ^6.1.4
  http: ^0.13.6
  intl: ^0.17.0
  mason_logger: ^0.2.5
  meta: ^1.9.1
  more: ^4.0.0
  openapi:
    path: ../openapi
  scidart: ^0.0.2-dev.12
  scoped:
    git:
      url: https://github.com/shorebirdtech/shorebird.git
      path: packages/scoped
  sembast: ^3.4.4
  stats: ^2.0.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0
