name: db
description: Database layer
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies: 
  collection: ^1.18.0
  meta: ^1.9.1
  postgres: ^3.1.2
  types:
    path: ../types

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0