name: db
description: Database layer
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.0
# resolution: workspace

dependencies: 
  collection: ^1.18.0
  equatable: ^2.0.7
  meta: ^1.9.1
  postgres: ^3.1.2
  types:
    path: ../types

dev_dependencies:
  docker_process: ^1.3.2
  mocktail: ^1.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
