[package]
name = "net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
postgres = "0.19.5"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = {version = "1.0.182", features = ["derive"]}
serde_json = "1.0.104"
